org.gradle.jvmargs=-Xmx1G
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
mod_version=1.0-SNAPSHOT
maven_group=io.katanas
archives_base_name=seq
fabric_version=0.141.1+1.21.11
pounce_version=d921e2c156
web_socket_version=1.5.7
wynntils_version=4.0.0-beta.3
commit_list="commits"
commit_authors="authors"
commit_date="date"
